routes/web.php
<?php

use App\Http\Controllers\OrderController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/403', function () {
    return view('errors.403');
})->name('403');

Route::middleware(['auth', 'admin-access:admin'])->group(function () {

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('orders', OrderController::class);
    Route::get('/removeProduct', [OrderController::class, 'removeProduct'])->name('orders.removeProduct');
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;

    protected $fillable = ['user_id'];

    protected $guarded = [];

    public function user()
    {
        return $this->hasOne(User::class, 'id', 'user_id');
    }

    public function products()
    {
        return $this->belongsTo(Product::class, 'id', 'order_id');
    }
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'order_id',
        'name',
        'quantity',
        'amount',
        'total',
    ];

    public function orders()
    {
        return $this->hasMany(Order::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Database\Eloquent\Casts\Attribute;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Order;
use App\Models\Product;
use Illuminate\Http\Request;
use App\Http\Requests\OrderRequest;
use App\Services\Order\OrderServices;

class OrderController extends Controller
{
    private $orderServices;

    public function __construct(OrderServices $orderServices)
    {
        $this->orderServices = $orderServices;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = $this->orderServices->getAllOrders();
        return view('orders.index', compact('orders'));
    }

    /**
     * Show the form for creating a new order.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = $this->orderServices->getUserProductData();
        return view('orders.create', compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(OrderRequest $request)
    {
        $this->orderServices->storeData($request);
        return redirect()->route('orders.index')
            ->with('success', 'Order created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = $this->orderServices->showOrder($id);
        return view('orders.show', compact('order'));
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('orders.index') }}">Orders</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>
                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

</html>

resources/views/orders/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container h-100 mt-5">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-10 col-md-8 col-lg-6">
                <h3>Add Order</h3>
                @if ($errors->any())
                    @foreach ($errors->all() as $error)
                        <div>{{$error}}</div>
                    @endforeach
                @endif
                <form action="{{ route('orders.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="user">User</label>
                        <select name="user_id" id="user_id" class="form-control">
                            <option value="">Select User</option>
                            @foreach ($users as $key => $user)
                                <option value="{{ $key }}">{{ $user }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div name="add_name" id="add_name">
                        <label for="product">Product</label>
                        <table class="table table-bordered table-hover" id="dynamic_field">
                          <tr>
                            <td><input type="text" name="product[0][name]" data-val="0" placeholder="Product Name" class="form-control product_name product_name-0" /></td>
                            <td><input type="text" name="product[0][quantity]" data-val="0" placeholder="Product Quantity" class="form-control product_quantity product_quantity-0"/></td>
                            <td><input type="text" name="product[0][amount]" data-val="0" value="" placeholder="Product Amount" class="form-control product_amount product_amount-0"/></td>
                            <td><input type="text" name="product[0][total]" data-val="0" value="" placeholder="Product Total" class="form-control product_total product_total-0" readonly/></td>
                            <td><button type="button" name="add" id="add" class="btn btn-primary add">+</button></td>
                          </tr>
                        </table>
                        {{-- <input type="submit" class="btn btn-success" name="submit" id="submit" value="Submit"> --}}
                    </div>
                    <div class="col-md-1"></div>
                    <div>
                        <p>Total: <span class="addtotal"></span></p>
                    </div>
                    {{-- <div class="form-group">
                        <label for="product">Product</label>
                        <select name="product_id" id="product_id" class="form-control" multiple>
                            <option value="">Select Product</option>
                            @foreach ($products as $key => $product)
                                <option value="{{ $key }}">{{ $product }}</option>
                            @endforeach
                        </select>
                    </div> --}}
                    <br>
                    <button type="submit" class="btn btn-primary">Create Order</button>
                </form>
            </div>
        </div>
    </div>
    <script>
         $(document).ready(function(){

   var i = 1;
     var length;
     //var addamount = 0;
    var addamount = 700;

//     product_quantity
// product_amount
    let addtotal = 0;
    $(document).on('keyup','.product_quantity',function(){
        let i = $(this).data('val');
        console.log(i,Number($('.product_quantity-'+i).val()) , Number($('.product_amount-'+i).val()));
        if(i != undefined){
            $('.product_total-'+i).val(Number($('.product_quantity-'+i).val()) * Number($('.product_amount-'+i).val()));
        } else {
            $('.product_total').val(Number($(this).val() * $('.product_amount').val()));
        }
        getTotal();

    })
    $(document).on('keyup','.product_amount',function(){
        let i = $(this).data('val');
        console.log(i,Number($('.product_amount-'+i).val()) , Number($('.product_quantity-'+i).val()));

        if(i != undefined){
            $('.product_total-'+i).val($('.product_amount-'+i).val() * $('.product_quantity-'+i).val());
        } else {
            $('.product_total').val($(this).val() * $('.product_quantity').val());
        }
        getTotal();
    })

    function getTotal(){
        let total = $('.product_total').map((_,el) => el.value).get();
        const sum = total.reduce((partialSum, a) => Number(partialSum) + Number(a), 0);
        $('.addtotal').text(sum);
    }

   $(document).on('click',".add",function(){

    i++;
       $('#dynamic_field').append(`
        <tr id="row${i}" class="row${i}">
            <td><input type="text" name="product[${i}][name]" placeholder="Product Name" data-val="${i}" class="form-control product_name product_name-${i}" /></td>
            <td><input type="text" name="product[${i}][quantity]" placeholder="Product Quantity" data-val="${i}" class="form-control product_quantity product_quantity-${i}"/></td>
            <td><input type="text" name="product[${i}][amount]" value="" placeholder="Product Amount" data-val="${i}" class="form-control product_amount product_amount-${i}"/></td>
            <td><input type="text" name="product[${i}][total]" data-val="${i}" value="" placeholder="Product Total" class="form-control product_total product_total-${i}" readonly/></td>
            <td style="display: flex;justify-content: center;"><button type="button" name="remove" id="${i}" class="btn btn-danger btn_remove" style="background:red;">X</button></td>
        </tr>`);
     });

   $(document).on('click', '.btn_remove', function(){
     addamount -= 700;
     console.log('amount: ' + addamount);

       var button_id = $(this).attr("id");
       $('#row'+button_id+'').remove();
     });



     $("#submit").on('click',function(event){
     var formdata = $("#add_name").serialize();
       console.log(formdata);

       event.preventDefault()

       $.ajax({
         url   :"action.php",
         type  :"POST",
         data  :formdata,
         cache :false,
         success:function(result){
           alert(result);
           $("#add_name")[0].reset();
         }
       });

     });
   });
    </script>
@endsection

resources/views/orders/index.blade.php
@extends('layouts.app')

@section('content')
    <nav class="navbar navbar-expand-lg navbar-light ">
        <div class="container-fluid">
            <a class="navbar-brand h1" href={{ route('orders.index') }}>Orders</a>
            <div class="justify-end ">
                <div class="col ">
                    <a class="btn btn-sm btn-success" href={{ route('orders.create') }}>Add Order</a>
                </div>
            </div>
        </div>
    </nav>
    <div class="container mt-5">
        <div class="row">
            <table class="table table-bordered mb-5">
                <thead>
                    <tr class="table-success">
                        <th scope="col">Id</th>
                        <th scope="col">User name</th>
                        <th scope="col">Total</th>
                        <th scope="col">Created At</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($orders as $order)
                        <tr>
                            <th scope="row">{{ $order->id }}</th>
                            <td>{{ $order->user->name }}</td>
                            <td>{{ array_sum($order->products->where('order_id',$order->id)->pluck('total')->toArray()) }}</td>
                            <td>{{ $order->created_at }}</td>
                            <td><a href="{{ route('orders.show', [$order->id]) }}">View</a></td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            {!! $orders->links() !!}
        </div>
    </div>
@endsection

resources/views/orders/show.blade.php
@extends('layouts.app')

@section('content')
    <nav class="navbar navbar-expand-lg navbar-light ">
        <div class="container-fluid">
            <a class="navbar-brand h1" href={{ route('orders.index') }}>Show Orders</a>
            <div class="justify-end ">
                <div class="col ">
                    <a class="btn btn-sm btn-success" href={{ route('orders.index') }}>Back</a>
                </div>
            </div>
        </div>
    </nav>
    <div class="container mt-5">
        <div class="row">
            <table class="table table-bordered mb-5">
                <thead>
                    <tr class="table-success">
                        <th scope="col">Order Id</th>
                        <th scope="col">Order Grand Total</th>
                        <th scope="col">Order User</th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="table-success">
                        <th scope="col">{{$order->id}}</th>
                        <th scope="col">{{array_sum($order->products->where('order_id',$order->id)->pluck('total')->toArray())}}</th>
                        <th scope="col">{{$order->user->name}}</th>
                    </tr>
                </tbody>
            </table>

            <table class="table table-bordered mb-5">
                <thead>
                    <tr class="table-success">
                        <th>Product Name</th>
                        <th>Product Quantity</th>
                        <th>Product Amount</th>
                        <th>Product Total</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($order->products->where('order_id',$order->id)->get() as $item)
                        <tr class="table-success">
                            <th scope="col">{{$item->name}}</th>
                            <th scope="col">{{$item->quantity}}</th>
                            <th scope="col">{{$item->amount}}</th>
                            <th scope="col">{{$item->total}}</th>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection